{% set name = "splink" %}
{% set version = "4.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moj-analytical-services/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 91fc72e24e177bed3fa0b366d55f56c2317c0c39882af3490321ebcd7a47e1a2

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.8
  run:
    - python
    - jsonschema >=3.2
    - pandas >1.3.5  # [py<313]
    - pandas >=2.2.3  # [py>=313]
    - python-duckdb >=0.9.2
    # [recipe upper bound] sqlglot 24 introduced breaking changes for some of the behaviors (can be revealed by
    # running the tests), which may cause runtime errors. Consarvatively introduce an upper bound.
    - sqlglot >=13.0.0,<24  # [py<313]
    # where we don't have a low enough version of the package, fall back to picking whatever is available.
    - sqlglot >=13.0.0  # [py>=313]
    - altair >=5.0.1  # [py<313]
    - altair >=5.5.0  # [py>=313]
    - jinja2 >=3.0.3
    - numpy >=1.17.3  # [py<312]
    - numpy >=1.26.0  # [py>=312]
    - python-igraph >=0.11.2
  run_constrained:
    - pyspark >=3.2.1
    - awswrangler >=3.0.0,<4.0.0
    - psycopg2 >=2.8.0

{% set skip_tests = "" %}

# sqlglot >=24 breaks splink's SQL AST handling on py>=3.13 (no sqlglot <24 build available for py>=313. see comment above).
# E  ValueError: Expected sql condition to refer to one column but got []
{% set skip_tests = skip_tests + " --deselect=tests/test_blocking.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_charts.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_compare_splink2.py::test_splink_2_predict_sqlite" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_compare_two_records.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_comparison_level.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_debug_mode.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_find_new_matches.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_full_example_duckdb.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_full_example_sqlite.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_new_comparison_levels.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_new_db_api.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_settings_options.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_train_vs_predict.py" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_realtime.py::test_realtime_cache_two_records" %}  # [py>=313]
{% set skip_tests = skip_tests + " --deselect=tests/test_realtime.py::test_realtime_cache_multiple_records" %}  # [py>=313]

# Known limitation - SQLite python module on Windows doesn't contain math function acos needed for this test.
# SQLITE_ENABLE_MATH_FUNCTIONS not enabled in sqlite3 (see: https://sqlite.org/lang_mathfunc.html).
{% set skip_tests = skip_tests + " --deselect=tests/test_km_distance_level.py::test_km_distance_levels[sqlite]" %}  # [win]

test:
  source_files:
    - tests
  imports:
    - splink
    - splink.comparison_library
    - splink.comparison_level_library
    - splink.internals
    - splink.datasets
  requires:
    - pip
    - pytest >=7.3
    - pyspark
    - psycopg2
    - sqlalchemy >=1.4.0
    - networkx >=2.5.1
    - rapidfuzz >=2.0.3
    - sqlglot
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv -m "not spark_only" -k "not postgres and not spark" {{ skip_tests }} tests
  

about:
  home: https://github.com/moj-analytical-services/splink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast, accurate and scalable probabilistic data linkage with support for multiple SQL backends
  description: |
    Splink is a Python package for probabilistic record linkage (entity resolution) that allows
    you to deduplicate and link records from datasets without unique identifiers.
  dev_url: https://github.com/moj-analytical-services/splink
  doc_url: https://moj-analytical-services.github.io/splink

extra:
  recipe-maintainers:
    - ThomasHepworth
    - ADBond
    - cdesouza21
